// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// foo
void foo();
RcppExport SEXP _tuple_test_foo() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    foo();
    return R_NilValue;
END_RCPP
}
// bar
RObject bar();
RcppExport SEXP _tuple_test_bar() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(bar());
    return rcpp_result_gen;
END_RCPP
}
// baz
RObject baz();
RcppExport SEXP _tuple_test_baz() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(baz());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tuple_test_foo", (DL_FUNC) &_tuple_test_foo, 0},
    {"_tuple_test_bar", (DL_FUNC) &_tuple_test_bar, 0},
    {"_tuple_test_baz", (DL_FUNC) &_tuple_test_baz, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tuple_test(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
