# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo <- function() {
    invisible(.Call('_array_test_foo', PACKAGE = 'array.test'))
}

bar <- function() {
    .Call('_array_test_bar', PACKAGE = 'array.test')
}

baz <- function() {
    .Call('_array_test_baz', PACKAGE = 'array.test')
}

