# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo <- function(x) {
    invisible(.Call('_span_test_foo', PACKAGE = 'span.test', x))
}

bar <- function() {
    .Call('_span_test_bar', PACKAGE = 'span.test')
}

