# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intArray <- function(x) {
    invisible(.Call('_RcppArray_intArray', PACKAGE = 'RcppArray', x))
}

unsignedArray <- function(x) {
    invisible(.Call('_RcppArray_unsignedArray', PACKAGE = 'RcppArray', x))
}

doubleArray <- function(x) {
    invisible(.Call('_RcppArray_doubleArray', PACKAGE = 'RcppArray', x))
}

stringArray <- function(x) {
    invisible(.Call('_RcppArray_stringArray', PACKAGE = 'RcppArray', x))
}

int64Array <- function(x) {
    invisible(.Call('_RcppArray_int64Array', PACKAGE = 'RcppArray', x))
}

intDoubleString <- function(x) {
    invisible(.Call('_RcppArray_intDoubleString', PACKAGE = 'RcppArray', x))
}

