# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo <- function() {
    invisible(.Call('_Rcpp_asArray_foo', PACKAGE = 'Rcpp.asArray'))
}

intArray <- function(x) {
    invisible(.Call('_Rcpp_asArray_intArray', PACKAGE = 'Rcpp.asArray', x))
}

doubleArray <- function(x) {
    invisible(.Call('_Rcpp_asArray_doubleArray', PACKAGE = 'Rcpp.asArray', x))
}

int64Array <- function(x) {
    invisible(.Call('_Rcpp_asArray_int64Array', PACKAGE = 'Rcpp.asArray', x))
}

